### ISSUE TITLE
include agencycode restriction in schema

### ISSUE THREAD

**Issue by tcatapano** [SAA-SDT/EAD-Revision#495]
Since it's for only one element and the pattern is schema-defined in EAC-CPF on which it is based.

**Comment by rockivist** [comment]
@tcatapano We intentionally removed the pattern from the schema because in practice may repositories don't follow the standard pattern for agency code identifiers. Daniel indicated that it's been a problem in EAC-CPF and that they will remove the pattern in future revisions. So it's better off in the Schematron. 

Closing.
